# Build step #1: build the React front end
FROM node:16-alpine as build-step
ENV PATH /frontend/node_modules/.bin:$PATH

COPY ./frontend/package.json ./frontend/package-lock.json ./frontend/postcss.config.js ./frontend/tailwind.config.js ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public

WORKDIR frontend
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-step /build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
